-- Post Module Initial Migration
-- TODO: Add your post-related migrations here

-- Example:
-- CREATE TABLE IF NOT EXISTS logs (
--   id INT PRIMARY KEY AUTO_INCREMENT,
--   level VARCHAR(50) NOT NULL,
--   message TEXT NOT NULL,
--   metadata TEXT,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
